dist: precise
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
env:
  global:
    - DJANGO_SETTINGS_MODULE="travis_test.travis_settings"
  matrix:
   - DJANGO="Django==1.8"
   - DJANGO="Django==1.9"
   - DJANGO="Django==1.10"
   - DJANGO="Django==1.11"
branches:
    only:
        - master
# command to install dependencies
install:
  - pip install -r travis_test/requirements.txt
  - pip install "$DJANGO"
  - pip install python-coveralls
  - pip install coverage
before_script:
  - mysql -e 'CREATE DATABASE `djangoblog` /*!40100 DEFAULT CHARACTER SET utf8 */;'
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - python manage.py compress --force
# command to run tests
script:
    - coverage run manage.py test
after_success:
    - coveralls
